[package]
name = "xtask"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
msb-crd = { path = "../crates/msb-crd" }
kube = { version = "4.0", features = ["derive"] }
k8s-openapi = { version = "0.28", features = ["v1_32"], default-features = false }
serde_yaml = "0.9"
serde_json = "1"
schemars = "1"
anyhow = "1"
