apiVersion: v1
kind: ServiceAccount
metadata:
  name: msb-controller
  namespace: msb-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: msb-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: msb-controller
subjects:
  - kind: ServiceAccount
    name: msb-controller
    namespace: msb-system
