//! `generate-api-docs`: render the Sandbox CRD types into a Markdown API
//! reference, in the style of KubeVirt's generated reference (one section per
//! type, fields as Name / Description / Schema, nested types linked by type
//! name). Single-sourced from the `///` doc-comments on the CRD types via
//! schemars, so the reference never drifts from the code. Do not hand-edit the
//! output; edit the doc-comments and regenerate.

use anyhow::{Context, Result};
use schemars::schema_for;
use serde_json::Value;
use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::{fs, path::Path};

const SPEC_OUT: &str = "userdocs/reference/sandbox-spec.mdx";
const STATUS_OUT: &str = "userdocs/reference/sandbox-status.mdx";

/// k8s well-known types arrive in `$defs` under their fully-qualified Go names
/// (`io.k8s.apimachinery.pkg.apis.meta.v1.Time`). Render them the way KubeVirt's
/// reference does: a short display name, and — for the scalar wrappers `Time` and
/// `Quantity` — as a leaf string with no section of their own.
struct KnownType {
    display: &'static str,
    /// A scalar wrapper (rendered as `string`, no section) rather than a struct.
    leaf: bool,
}

fn known_type(fq_name: &str) -> Option<KnownType> {
    let short = fq_name.rsplit('.').next().unwrap_or(fq_name);
    match short {
        "Time" | "MicroTime" => Some(KnownType {
            display: "Time",
            leaf: true,
        }),
        "Quantity" => Some(KnownType {
            display: "Quantity",
            leaf: true,
        }),
        "Condition" => Some(KnownType {
            display: "Condition",
            leaf: false,
        }),
        _ => None,
    }
}

pub fn generate() -> Result<()> {
    let spec = serde_json::to_value(schema_for!(msb_crd::sandbox::SandboxSpec))
        .context("serialize SandboxSpec schema")?;
    let status = serde_json::to_value(schema_for!(msb_crd::sandbox::SandboxStatus))
        .context("serialize SandboxStatus schema")?;

    write_page(
        SPEC_OUT,
        "SandboxSpec",
        "Sandbox spec",
        "The desired state of a Sandbox. Set on the `.spec` of a `Sandbox` resource.",
        "table",
        &spec,
    )?;
    write_page(
        STATUS_OUT,
        "SandboxStatus",
        "Sandbox status",
        "The observed state of a Sandbox, written by the controller to `.status`. Read-only.",
        "table-list",
        &status,
    )?;
    Ok(())
}

fn write_page(
    path: &str,
    root_type: &str,
    title: &str,
    intro: &str,
    icon: &str,
    schema: &Value,
) -> Result<()> {
    let defs = schema
        .get("$defs")
        .and_then(Value::as_object)
        .cloned()
        .unwrap_or_default();

    let mut out = String::new();
    writeln!(out, "---").unwrap();
    writeln!(out, "title: {title}").unwrap();
    writeln!(out, "description: {intro}").unwrap();
    writeln!(out, "icon: \"{icon}\"").unwrap();
    writeln!(out, "---\n").unwrap();
    writeln!(
        out,
        "{{/* Generated by `cargo xtask generate-api-docs`. Do not edit; change the doc-comments on the CRD types and regenerate. */}}\n"
    )
    .unwrap();
    writeln!(out, "{intro}\n").unwrap();

    // The root type's own table, then every referenced type once, in a stable
    // (reachable, then alphabetical) order.
    let order = type_order(root_type, schema, &defs);
    for (i, ty) in order.iter().enumerate() {
        let obj = if i == 0 { schema } else { &defs[ty] };
        // Skip enum-only types: their values show inline where they are used.
        if is_enum(obj) {
            continue;
        }
        let heading = known_type(ty).map(|k| k.display).unwrap_or(ty);
        writeln!(out, "## {heading}\n").unwrap();
        write_type_table(&mut out, obj, &defs);
        out.push('\n');
    }

    let p = Path::new(path);
    fs::create_dir_all(p.parent().unwrap()).context("create reference dir")?;
    fs::write(p, &out).with_context(|| format!("write {path}"))?;
    println!("wrote {path}");
    Ok(())
}

/// Root first, then object types reachable from it (breadth-first), then any
/// leftover object defs alphabetically. Enum defs are omitted (rendered inline).
fn type_order(root_type: &str, root: &Value, defs: &serde_json::Map<String, Value>) -> Vec<String> {
    let mut order = vec![root_type.to_string()];
    let mut seen: BTreeSet<String> = [root_type.to_string()].into();
    let mut queue = vec![root.clone()];
    while let Some(obj) = queue.pop() {
        for (_, prop) in properties(&obj) {
            if let Some(ty) = ref_type(&prop) {
                // Leaf well-known types (Time, Quantity) render inline as `string`
                // and get no section of their own.
                let is_leaf = known_type(&ty).is_some_and(|k| k.leaf);
                if !seen.contains(&ty) && !is_leaf && defs.get(&ty).is_some_and(|d| !is_enum(d)) {
                    seen.insert(ty.clone());
                    order.push(ty.clone());
                    queue.push(defs[&ty].clone());
                }
            }
        }
    }
    // any object def not reachable (shouldn't happen, but keep it deterministic)
    for (name, d) in defs {
        let is_leaf = known_type(name).is_some_and(|k| k.leaf);
        if !is_enum(d) && !is_leaf && !seen.contains(name) {
            order.push(name.clone());
        }
    }
    order
}

fn write_type_table(out: &mut String, obj: &Value, defs: &serde_json::Map<String, Value>) {
    let props = properties(obj);
    if props.is_empty() {
        writeln!(out, "_No fields._").unwrap();
        return;
    }
    let required: BTreeSet<String> = obj
        .get("required")
        .and_then(Value::as_array)
        .map(|a| {
            a.iter()
                .filter_map(|v| v.as_str().map(String::from))
                .collect()
        })
        .unwrap_or_default();

    writeln!(out, "| Field | Description | Schema |").unwrap();
    writeln!(out, "|---|---|---|").unwrap();
    for (name, prop) in props {
        let req = if required.contains(&name) {
            format!("`{name}` _required_")
        } else {
            format!("`{name}`")
        };
        writeln!(
            out,
            "| {req} | {} | {} |",
            describe(&prop),
            schema_col(&prop, defs)
        )
        .unwrap();
    }
}

/// The Schema column: a primitive, an enum list, a linked type, or an array/map.
fn schema_col(prop: &Value, defs: &serde_json::Map<String, Value>) -> String {
    // direct $ref to a named type (also handles Option<Struct> via anyOf/allOf)
    if let Some(ty) = ref_type(prop) {
        return type_ref_display(&ty, defs);
    }
    match primitive_type(prop).as_deref() {
        Some("array") => {
            let items = prop.get("items").cloned().unwrap_or(Value::Null);
            if let Some(ty) = ref_type(&items) {
                format!("{}[]", type_ref_display(&ty, defs))
            } else {
                let inner = primitive_type(&items).unwrap_or_else(|| "object".to_string());
                format!("{inner}[]")
            }
        }
        Some(t) => t.to_string(),
        None => "object".to_string(),
    }
}

/// The primitive type of a property, unwrapping `Option<T>`, which schemars emits
/// either as `"type": ["integer", "null"]` or `"anyOf": [{type}, {"type":"null"}]`.
fn primitive_type(prop: &Value) -> Option<String> {
    match prop.get("type") {
        Some(Value::String(s)) => return Some(s.clone()),
        Some(Value::Array(arr)) => {
            for v in arr {
                if let Some(s) = v.as_str() {
                    if s != "null" {
                        return Some(s.to_string());
                    }
                }
            }
        }
        _ => {}
    }
    for key in ["anyOf", "oneOf", "allOf"] {
        if let Some(arr) = prop.get(key).and_then(Value::as_array) {
            for item in arr {
                if let Some(s) = item.get("type").and_then(Value::as_str) {
                    if s != "null" {
                        return Some(s.to_string());
                    }
                }
            }
        }
    }
    None
}

/// An enum type renders inline as its value list; a struct type links to its
/// section (anchored on the lowercased type name, matching the `## Type` heading).
fn type_ref_display(ty: &str, defs: &serde_json::Map<String, Value>) -> String {
    if let Some(known) = known_type(ty) {
        if known.leaf {
            return "string".to_string();
        }
        return format!("[{}](#{})", known.display, known.display.to_lowercase());
    }
    match defs.get(ty) {
        Some(d) if is_enum(d) => enum_inline(d).unwrap_or_else(|| "string".to_string()),
        Some(_) => format!("[{ty}](#{})", ty.to_lowercase()),
        None => ty.to_string(),
    }
}

fn describe(prop: &Value) -> String {
    let raw = prop
        .get("description")
        .and_then(Value::as_str)
        .unwrap_or("");
    let (body, immutable) = normalize_mutability(raw);
    let mut d = body
        .replace('\n', " ")
        .replace('|', "\\|")
        .trim()
        .to_string();
    if let Some(def) = prop.get("default").and_then(default_display) {
        let _ = write!(d, " Default `{def}`.");
    }
    if immutable {
        if !d.is_empty() && !d.ends_with('.') {
            d.push('.');
        }
        d.push_str(" Immutable.");
    }
    d.trim().to_string()
}

/// Split the mutability label out of a description. Returns the cleaned body and
/// whether the field is immutable (surfaced as a terse trailing "Immutable.").
/// - "…text. This field is immutable[.:] <why>" → ("…text. <Why>", true)
/// - "Number of vCPUs. Mutable, up to maxCpus: <effect>." → ("Number of vCPUs. <Effect>.", false)
fn normalize_mutability(desc: &str) -> (String, bool) {
    if let Some(idx) = desc.find("This field is immutable") {
        let (head, tail) = desc.split_at(idx);
        let why = tail
            .trim_start_matches("This field is immutable")
            .trim_start_matches([':', '.'])
            .trim();
        return (sentence_join(head.trim(), why), true);
    }
    if let Some(idx) = desc.find("Mutable") {
        let (head, tail) = desc.split_at(idx);
        let effect = tail.split_once(':').map(|(_, e)| e.trim()).unwrap_or("");
        return (sentence_join(head.trim(), effect), false);
    }
    (desc.to_string(), false)
}

/// Join a head and a kept clause, capitalizing the clause to read as a sentence.
fn sentence_join(head: &str, rest: &str) -> String {
    if rest.is_empty() {
        return head.to_string();
    }
    let mut c = rest.chars();
    let rest = match c.next() {
        Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
        None => String::new(),
    };
    if head.is_empty() {
        rest
    } else {
        format!("{head} {rest}")
    }
}

fn default_display(v: &Value) -> Option<String> {
    match v {
        Value::Bool(b) => Some(b.to_string()),
        Value::Number(n) => Some(n.to_string()),
        Value::String(s) if !s.is_empty() => Some(s.clone()),
        _ => None,
    }
}

// --- schema helpers ---------------------------------------------------------

fn properties(obj: &Value) -> Vec<(String, Value)> {
    obj.get("properties")
        .and_then(Value::as_object)
        .map(|m| m.iter().map(|(k, v)| (k.clone(), v.clone())).collect())
        .unwrap_or_default()
}

/// The type name a `$ref` points at, if the value is (or wraps) a `$ref`.
fn ref_type(v: &Value) -> Option<String> {
    // schemars may emit "$ref" directly, or wrap in allOf/oneOf for Options.
    if let Some(r) = v.get("$ref").and_then(Value::as_str) {
        return Some(ref_name(r));
    }
    for key in ["allOf", "anyOf", "oneOf"] {
        if let Some(arr) = v.get(key).and_then(Value::as_array) {
            for item in arr {
                if let Some(r) = item.get("$ref").and_then(Value::as_str) {
                    return Some(ref_name(r));
                }
            }
        }
    }
    None
}

fn ref_name(r: &str) -> String {
    r.rsplit('/').next().unwrap_or(r).to_string()
}

/// A def is a string enum if it has a flat `enum`, or a `oneOf` whose every
/// branch is a scalar (a `const` or a nested `enum`, no `properties`). schemars
/// 1.0 emits a mixed `oneOf` — undocumented variants collapse into one `enum`
/// branch, each documented variant becomes its own `const` branch.
fn is_enum(def: &Value) -> bool {
    if def.get("enum").is_some() {
        return true;
    }
    def.get("oneOf").and_then(Value::as_array).is_some_and(|a| {
        !a.is_empty()
            && a.iter()
                .all(|v| v.get("const").is_some() || v.get("enum").is_some())
    })
}

fn enum_inline(def: &Value) -> Option<String> {
    if let Some(arr) = def.get("enum").and_then(Value::as_array) {
        let vals: Vec<String> = arr
            .iter()
            .filter_map(|v| v.as_str().map(|s| format!("`{s}`")))
            .collect();
        if !vals.is_empty() {
            return Some(format!("enum ({})", vals.join(", ")));
        }
    }
    if let Some(arr) = def.get("oneOf").and_then(Value::as_array) {
        let mut vals: Vec<String> = Vec::new();
        for v in arr {
            if let Some(s) = v.get("const").and_then(Value::as_str) {
                vals.push(format!("`{s}`"));
            } else if let Some(inner) = v.get("enum").and_then(Value::as_array) {
                vals.extend(
                    inner
                        .iter()
                        .filter_map(|e| e.as_str().map(|s| format!("`{s}`"))),
                );
            }
        }
        if !vals.is_empty() {
            return Some(format!("enum ({})", vals.join(", ")));
        }
    }
    None
}
